### ISSUE TITLE
@actions/core package not found 

### ISSUE THREAD

**Issue by TimBobkov** [mosteo-actions/docker-run#1]
Try to run action and receive: 
internal/modules/cjs/loader.js:968
|   throw err;
|   ^
| 
| Error: Cannot find module '@actions/core'
| Require stack:
| - /actions/mosteo-actions-docker-run@v1/main.js

Have check action cache dir:
$ ls node_modules/@actions
github  http-client

After running "npm i":
$ ls node_modules/@actions
core  github  http-client

So I think you don't push node modules with @action/core package.

**Comment by mosteo** [comment]
Fixed in #2
